name: 'Rebol-Identify CI'
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - ci-test.r3
      - identify.reb
      - .github/workflows/main.yml

  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  CI:
    strategy:
      matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rebol for the test
      uses: oldes/install-rebol@v3.18.0

    - name: Test Identify module
      run:  ./rebol3 ci-test.r3
